apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperclip-home
  namespace: dev
  labels:
    app: paperclip-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-disk-topology-alltype
