apiVersion: v1
kind: Service
metadata:
  name: paperclip-service
  namespace: dev
  labels:
    app: paperclip-service
spec:
  selector:
    app: paperclip-service
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP
